### ISSUE TITLE
Estudar para a prova e fazer o VT para o dia 06/06

### ISSUE THREAD

**Issue by evaldo** [evaldo/aulamanutencao20181#1]
Estudar para a prova e fazer o VT para o dia 06/06. A matéria da prova terá os seguintes itens:
- Arquiteturas (centralizada e distribuída) de Sistemas de Controle de Versão (SCV), vantagens e desvantagens
- Criação de repositórios em Workspaces
- Operações básicas de um modelo de versionamento de software em SCV
- Estudar os slides 68 a 75

**Comment by Universo8** [comment]
ok, ciente. vamos estudar.

**Comment by brunoaula** [comment]
ciente, vamos estuda!!

**Comment by gustavocrbo** [comment]
Ciente e vamos estudar.

**Comment by Raihenrique** [comment]
Ciente e vamos estudar!

**Comment by evaldo** [comment]
Peço que resolvam a Mudança.

**Comment by Raihenrique** [comment]
ok

**Comment by Universo8** [comment]
ok

**Comment by gustavocrbo** [comment]
ok

**Comment by brunoaula** [comment]
ok!

**Comment by evaldo** [comment]
Fechamento. da mudança. boa prova!!
